#!/bin/bash

# system_report.sh script
#By: Micheal Verconich
#Student ID: 200386136
#Date: June 12th 2025
#Course:COMP 2137

# Check for sudo and auto-elevate if not running as root
if [ "$EUID" -ne 0 ]; then
  exec sudo "$0" "$@"
fi

# Load OS info
source /etc/os-release

# System Identification
hostname=$(hostname)
username=$(logname)
datetime=$(date)

# System Information
os="$NAME $VERSION"
uptime=$(uptime -p)
cpu=$(lshw -class processor | grep "product" | head -n 1 | cut -d: -f2 | xargs)
ram=$(free -h | grep Mem | awk '{print $2}')
disks=$(lshw -class disk 2>/dev/null | awk -F: '/product:/{gsub(/^[ \t]+/, "", $2); printf "%s", $2} /size:/{gsub(/^[ \t]+/, "", $2); printf " - %s\n", $2}')
video=$(lshw -class display | grep "product" | head -n 1 | cut -d: -f2 | xargs)

# Networking Info
ipaddr=$(ip -4 addr show ens33 | grep inet | awk '{print $2}' | cut -d/ -f1)
gateway=$(ip r | grep default | awk '{print $3}')
dns=$(grep nameserver /etc/resolv.conf | head -n 1 | awk '{print $2}')

# System Status
users=$(who | awk '{print $1}' | sort | uniq | paste -sd, -)
diskspace=$(df -h --output=target,avail -x tmpfs -x devtmpfs | awk 'NR>1 {printf "  %-40s %6s\n", substr($0, 1, length($0)-length($NF)-1), $NF}')
proccount=$(ps aux | wc -l)
loadavg=$(uptime | awk -F'load average: ' '{print $2}')
ports=$(ss -tuln | awk 'NR>1 {split($5,a,":"); print a[length(a)]}' | sort -nu | paste -sd, -)
ufwstatus=$(ufw status | grep Status | awk '{print $2}')

# Report Output
echo
echo "System Report for $hostname generated by $username, on $datetime"
echo
echo "System Information"
echo "------------------"
echo "OS: $os"
echo "Uptime: $uptime"
echo "CPU: $cpu"
echo "RAM: $ram"
echo "Disk(s):"
echo "$disks"
echo "Video: $video"
echo "Host Address: $ipaddr"
echo "Gateway IP: $gateway"
echo "DNS Server: $dns"
echo
echo "System Status"
echo "-------------"
echo "Users Logged In: $users"
echo "Disk Space: $diskspace"
echo "Process Count: $proccount"
echo "Load Averages: $loadavg"
echo "Listening Network Ports: $ports"
echo "UFW Status: $ufwstatus"
echo
